version: "3.9"
name: prod

services:
  nginx:
    image: nginx
    ports:
      - "80:80"
    volumes:
      - ./docker/nginx.conf:/etc/nginx/conf.d/default.conf
      - app_nginx:/usr/share/nginx/html
    networks:
      - app_network
    links:
      - app
    depends_on:
      - "app"

  app:
    build:
      dockerfile: Dockerfile
      no_cache: true
    volumes:
      - app_nginx:/usr/src/app/dist


networks:
  app_network:
    driver: bridge

volumes:
  app_nginx: